package com.example.dcc.fragment;

import android.app.Fragment;
import android.content.Intent;
import android.os.Bundle;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import android.widget.TextView;
import com.example.dcc.R;
import com.example.dcc.helpers.Member;
import com.example.dcc.helpers.User;

/**
 * Created by Harmon on 5/17/13.
 */
public class MemberDetailFragment extends Fragment implements View.OnClickListener{

    User member;
    TextView memname,memhandle, memproj1, memproj2;
    Button mememail;
    ImageView userIcon;

    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState){
        View view = inflater.inflate(R.layout.member_detail_layout, container, false);
        super.onCreate(savedInstanceState);

        member = (User)this.getArguments().getSerializable("member");

        memname = (TextView)view.findViewById(R.id.memname);
        memhandle = (TextView)view.findViewById(R.id.memhandle);
        memproj1 = (TextView)view.findViewById(R.id.memproj1);
        memproj2 = (TextView)view.findViewById(R.id.memproj2);

        userIcon = (ImageView)view.findViewById(R.id.memicon);

        mememail = (Button)view.findViewById(R.id.mememail);
        mememail.setOnClickListener(this);

        memname.setText(member.getName());
        memhandle.setText(member.getHandle());
        memproj1.setText(member.getProject());
        memproj2.setText(member.getProject2());

        mememail.setText(member.getEmail());

        if(member.getImage()!=null)
            userIcon.setImageBitmap(member.getImage());
        return view;
    }

    @Override
    public void onClick(View view) {
        switch(view.getId()){
            case R.id.mememail:
                String email = member.getEmail();
                Intent i = new Intent(android.content.Intent.ACTION_SEND);
                i.setType("text/plain");
                i.putExtra(android.content.Intent.EXTRA_EMAIL, email);
                i.putExtra(android.content.Intent.EXTRA_SUBJECT, "S2013_Android_AutoGenerated_Subject");
                i.putExtra(android.content.Intent.EXTRA_TEXT, "--Sent From DCC App");
                startActivityForResult((Intent.createChooser(i, "Email")), 1);
        }
    }
}
